title: "Paul ♥ Kaylee"
description: >
  Paul × Kaylee • February 29th, 2024 •
  Many waters cannot quench love,
  neither can the floods drown it.
  &mdash; Songs of Solomon 8:7

info:
  date_format: "%b %d, %y"
  short_name: "Paul♥ Kaylee"
  color:
    theme: "#add8e6"
    bg: "#ffffff"
  url: "https://kp.kaylorful.com"
  categories:
    - social
    - photo
    - travel
    - news
  logo:
    image: "logo.svg"
    size: 200
    alt_image: "logo-square.svg"
    alt_size: 70
    sizes: [ 48, 96, 144, 192, 300, 512 ]
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-512.png"
    favicon: "favicon.ico"
    keywords: >
      wedding,
      church,
      vietnam,
      california,
      saigon
  font_families:
    - Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
    - Cormorant+Garamond+Display
    - Be+Vietnam+Pro
    - Festive
    - Montez
    - Share+Tech+Mono

sass:
  style: compact

collections_dir: content
collections:
  modules:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "modules"
    values:
      layout: "modules"

include:
  - index.html
  - 404.html
  - pwabuilder-sw.js
  - content

exclude:
  - README.md
  - LICENSE
  - runme.sh

